export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const ALERT_RESET = 'ALERT_RESET'
