export const alertConstants = {
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
  USER_UPDATE_PROFILE_FAIL: 'USER_UPDATE_PROFILE_FAIL',
  ALERT_RESET: 'ALERT_RESET',
}
